<?php


namespace Apps\FormContact\Ctrl;


use Boom\Ctrl\Controller;
use Cake\ORM\TableRegistry;

class FormContact extends Controller
{
    function __construct($appname, $request, $response, array $params, $name)
    {
        $this->hasModel = false;
        parent::__construct($appname, $request, $response, $params, $name);
    }

    function action_main($params = null)
    {
        //parent::action_main($params); // TODO: Change the autogenerated stub
        return $this->view('form');
    }

    function action_form($params = null)
    {
        if (isset($_POST['name']) && !empty($_POST['name']) &&
            isset($_POST['email']) && !empty($_POST['email']) &&
            isset($_POST['message']) && !empty($_POST['message'])) {

            $config = TableRegistry::get('FormContact');
            $config = $config->find()->first();

            $name = $_POST['name'];
            $email = $_POST['email'];
            $message = "
            <html>
                <head>
                    <title>Email du site</title>
                </head>
                <body>
                    {$_POST['message']}
                </body>
            </html>
            ";
            $destinataire = $config->email;


            $sujet = 'Message depuis kimtan.fr';

            // Pour envoyer un mail HTML, l'en-tête Content-type doit être défini
            $headers  = 'MIME-Version: 1.0' . "\r\n";
            $headers .= 'Content-type: text/html; charset=UTF-8' . "\r\n";
            // En-têtes additionnels
            $headers .= "To: Web <{$destinataire}>" . "\r\n";
            $headers .= "From: {$name} <{$email}>" . "\r\n";
            $headers .= "Reply-To: {$name} <{$email}>" . "\r\n";

            if(mail($destinataire, $sujet, $message, $headers))
            {
                return true;
            }
        }
        return false;
    }

}