<?php


namespace Apps\FormContact\Ctrl;


use Boom\Ctrl\Controller;

class FormContact extends Controller
{
    function __construct($appname, $request, $response, array $params, $name)
    {
        $this->hasModel = false;
        parent::__construct($appname, $request, $response, $params, $name);
    }

    function action_main($params = null)
    {
        //parent::action_main($params); // TODO: Change the autogenerated stub
        return $this->view('form');
    }

}